(deftheme gnp-light
  "Created 2013-04-25.")

(custom-theme-set-variables
 'gnp-light
 '(cua-normal-cursor-color "black")
 '(cua-overwrite-cursor-color "red")
 '(cua-read-only-cursor-color "dark olive green"))

(custom-theme-set-faces
 'gnp-light
 '(default ((t (:background "snow" :foreground "black" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :inherit nil))))
 '(cursor ((t (:background "black"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
 '(highlight ((t (:background "#babdb6"))))
 '(region ((t ( :background "SteelBlue3" :foreground "snow"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "PaleGreen2"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "royal blue"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "khaki4"))))
 '(font-lock-constant-face ((t (:weight normal :foreground "dark red"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "dark blue"))))
 '(font-lock-keyword-face ((t (:foreground "dark green"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "OrangeRed3"))))
 '(font-lock-type-face ((t (:foreground "violet red"))))
 '(font-lock-variable-name-face ((t (:foreground "deep pink"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#204a87"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#3465a4" :inherit (link)))))
 '(fringe ((t (:background "#d3d7cf"))))
 '(header-line ((t (:box nil :foreground "snow" :background "dark slate grey" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#2e3436" :background "wheat"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "grey10"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:background "wheat" :inherit (mode-line) :box nil))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground "#2e3436" :background  "#d3d7cf" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#ffffff" :background "#ce5c00"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "black" :background "#e9b96e"))))
 '(match ((t (:background "blue4"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(show-paren-match ((t (:background nil :foreground "dark red" :weight bold))))
 '(wgrep-delete-face ((t (:foreground "red"))))
 '(wgrep-face ((t (:foreground "yellow"))))
 '(wgrep-file-face ((t (:foreground "snow" :background "gray30"))))
 '(wgrep-reject-face ((t (:foreground "hot pink"))))
 '(slime-repl-input-face ((t (:foreground "dark green" :weight normal))))
 '(slime-repl-output-face ((t (:foreground "dark slate gray"))))
 '(slime-repl-inputed-output-face ((t (:foreground "orange red"))))
 '(slime-repl-output-mouseover-face ((t (:inherit (slime-repl-inputed-output-face)))))
 '(slime-repl-prompt-face ((t (:foreground "DodgerBlue4"))))
 '(ido-first-match ((t (:foreground "tomato" :weight normal))))
 '(ido-only-match ((t (:foreground "tomato"))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "saddle brown"))))
 '(error ((t (:foreground "firebrick1" :weight normal)))))

(provide-theme 'gnp-light)
