(deftheme gnp-dark
  "Created 2013-04-25.")

(custom-theme-set-variables
 'gnp-dark
 '(cua-normal-cursor-color "snow")
 '(cua-overwrite-cursor-color "red")
 '(cua-read-only-cursor-color "green"))

(custom-theme-set-faces
 'gnp-dark
 '(default ((t (:family "Inconsolata" :background "black" :foreground "azure1" :width normal :weight normal :height 80 :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil  :stipple nil :inherit nil))))
 '(cursor ((t (:background "snow"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "medium blue"))))
 '(highlight ((t (:background "darkolivegreen"))))
 '(region ((t (:background "DodgerBlue4" :foreground "snow"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "gray20"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#637EA3"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "IndianRed3"))))
 '(font-lock-constant-face ((t (:weight normal :foreground "MediumPurple1"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "deepskyblue"))))
 '(font-lock-keyword-face ((t (:foreground "lightgreen"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "LightGoldenrod2"))))
 '(font-lock-type-face ((t (:foreground "plum1"))))
 '(font-lock-variable-name-face ((t (:foreground "PaleVioletRed1"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((((class color) (background light)) (:background "grey95")) (((class color) (background dark)) (:background "grey10")) (t (:background "gray"))))
 '(header-line ((t (:inherit (mode-line) :background "dark slate grey" :foreground "white smoke" :box nil))))
 '(tooltip ((t (:inherit (variable-pitch) :background "lightyellow" :foreground "black"))))
 '(mode-line ((t (:background "#660000" :foreground "grey80" :box (:line-width 1 :color "#880000")))))
 '(mode-line-buffer-id ((t (:foreground "white" :weight normal))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit (mode-line) :background "#990000" :box (:line-width 1 :color "#bb0000")))))
 '(mode-line-inactive ((t (:inherit (mode-line) :background "#220000" :foreground "grey80" :weight light :box (:line-width 1 :color "#440000")))))
 '(isearch ((t (:foreground "bisque2" :background "firebrick"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "OliveDrab4" :foreground "black"))))
 '(match ((t (:background "blue4"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(show-paren-match ((t (:background nil :foreground "red" :weight bold))))
 '(wgrep-delete-face ((t (:foreground "red"))))
 '(wgrep-face ((t (:foreground "yellow"))))
 '(wgrep-file-face ((t (:foreground "white" :background "gray30"))))
 '(wgrep-reject-face ((t (:foreground "hot pink"))))
 '(slime-repl-input-face ((t (:foreground "lime green"))))
 '(slime-repl-output-face ((t (:foreground "light slate gray"))))
 '(slime-repl-inputed-output-face ((t (:foreground "orange red"))))
 '(slime-repl-output-mouseover-face ((t (:inherit (slime-repl-inputed-output-face)))))
 '(slime-repl-prompt-face ((t (:foreground "cyan3"))))
 '(ido-first-match ((t (:foreground "tomato" :weight normal))))
 '(ido-only-match ((t (:foreground "tomato"))))
 '(ido-subdir ((((min-colors 88) (class color)) (:foreground "gold2"))))
 '(error ((t (:foreground "firebrick1" :weight normal)))))

(provide-theme 'gnp-dark)
